apiVersion: app/v1beta2
kind: Deployment
metadat:
  name: myapp         # deployment应用名
  labels:
    app: myapp        # deployment应用标签定义
  spec:
    replicas: 1       # pod副本数
    selector:
      matchLabels:
        app: myapp    # pod选择器标签
    template:
      metadata:
        labels:
          app: myapp  # pod标签定义
      spec:
        containers:
          - name: myapp # 容器名
            image: xxxxxxx:1.7.9  #镜像地址
            ports:
              - name: http
                containerPort: 80
                protocol: TCP