apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myapp-ingress   # ingress应用名
spec:
  rules:
    - host: www.xxxxx.com   # 域名
      http:
        paths:
          - path: /
            backend:
              serviceName: myapp-svr  # 服务名
              servicePort: 80